### ISSUE TITLE
intra() function causes it to break

### ISSUE THREAD

**Issue by sombra2** [Simple-Stock-Bots/Simple-Telegram-Stock-Bot#1]
Hi! love your code. I have cloned your repository to hopefully translate it into my language and do some small tweaks. I am going through all your code and when I run it and execute the funcion intra() in line 259 of bot.py, it breaks and throws this:

**/usr/local/lib/python3.9/site-packages/mplfinance/plotting.py:332: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig = plt.figure()
2021-09-22 11:22:04.546 Python[25910:705060] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff205df83b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20317d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20607f36 -[NSException raise] + 9
	3   AppKit                              0x00007fff22d95eb2 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22d80aa2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1296
	5   AppKit                              0x00007fff22d8058b -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   _macosx.cpython-39-darwin.so        0x0000000114c02f15 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 69
	7   _macosx.cpython-39-darwin.so        0x0000000114c065c9 FigureManager_init + 265
	8   Python                              0x00000001060b430c wrap_init + 12
	9   Python                              0x0000000106072272 wrapperdescr_call + 316
	10  Python                              0x000000010606b67c _PyObject_MakeTpCall + 266
	11  Python                              0x00000001061131af call_function + 455
	12  Python                              0x000000010611054f _PyEval_EvalFrameDefault + 25980
	13  Python                              0x000000010606bd21 function_code_fastcall + 97
	14  Python                              0x000000010606b540 _PyObject_FastCallDictTstate + 212
	15  Python                              0x000000010606bf6a _PyObject_Call_Prepend + 139
	16  Python                              0x00000001060b4270 slot_tp_init + 87
	17  Python                              0x00000001060ada4e type_call + 150
	18  Python                              0x000000010606b67c _PyObject_MakeTpCall + 266
	19  Python                              0x00000001061131af call_function + 455
	20  Python                              0x000000010611054f _PyEval_EvalFrameDefault + 25980
	21  Python                              0x000000010606bd21 function_code_fastcall + 97
	22  Python                              0x000000010606d979 method_vectorcall + 164
	23  Python                              0x000000010611317b call_function + 403
	24  Python                              0x000000010611054f _PyEval_EvalFrameDefault + 25980
	25  Python                              0x0000000106113c54 _PyEval_EvalCode + 1887
	26  Python                              0x000000010606bcb1 _PyFunction_Vectorcall + 248
	27  Python                              0x000000010606d979 method_vectorcall + 164
	28  Python                              0x000000010606b9f8 PyVectorcall_Call + 146
	29  Python                              0x0000000106110851 _PyEval_EvalFrameDefault + 26750
	30  Python                              0x0000000106113c54 _PyEval_EvalCode + 1887
	31  Python                              0x000000010606bcb1 _PyFunction_Vectorcall + 248
	32  Python                              0x000000010606b9f8 PyVectorcall_Call + 146
	33  Python                              0x0000000106110851 _PyEval_EvalFrameDefault + 26750
	34  Python                              0x0000000106113c54 _PyEval_EvalCode + 1887
	35  Python                              0x000000010606bcb1 _PyFunction_Vectorcall + 248
	36  Python                              0x000000010611317b call_function + 403
	37  Python                              0x000000010611054f _PyEval_EvalFrameDefault + 25980
	38  Python                              0x0000000106113c54 _PyEval_EvalCode + 1887
	39  Python                              0x000000010606bcb1 _PyFunction_Vectorcall + 248
	40  Python                              0x000000010611317b call_function + 403
	41  Python                              0x000000010611069f _PyEval_EvalFrameDefault + 26316
	42  Python                              0x000000010606bd21 function_code_fastcall + 97
	43  Python                              0x0000000106110851 _PyEval_EvalFrameDefault + 26750
	44  Python                              0x000000010606bd21 function_code_fastcall + 97
	45  Python                              0x000000010611317b call_function + 403
	46  Python                              0x0000000106110533 _PyEval_EvalFrameDefault + 25952
	47  Python                              0x000000010606bd21 function_code_fastcall + 97
	48  Python                              0x000000010606da05 method_vectorcall + 304
	49  Python                              0x0000000106110851 _PyEval_EvalFrameDefault + 26750
	50  Python                              0x000000010606bd21 function_code_fastcall + 97
	51  Python                              0x000000010611317b call_function + 403
	52  Python                              0x0000000106110533 _PyEval_EvalFrameDefault + 25952
	53  Python                              0x000000010606bd21 function_code_fastcall + 97
	54  Python                              0x000000010611317b call_function + 403
	55  Python                              0x0000000106110533 _PyEval_EvalFrameDefault + 25952
	56  Python                              0x000000010606bd21 function_code_fastcall + 97
	57  Python                              0x000000010606da05 method_vectorcall + 304
	58  Python                              0x000000010618d61a t_bootstrap + 70
	59  Python                              0x000000010614d562 pythread_wrapper + 25
	60  libsystem_pthread.dylib             0x00007fff2046c8fc _pthread_start + 224
	61  libsystem_pthread.dylib             0x00007fff20468443 thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException**

do you know what's going on here? Is it something relative to Matplotlib and threadding? kind of stuck here, any clues?

EDIT: more legible text

**Comment by MisterBiggs** [comment]
Definitely seems to be from something matplotlib is doing. I don't have this issue on any of my machines so I am not sure how to reproduce but could you possibly try this solution? https://stackoverflow.com/a/66567690/8774114

**Comment by sombra2** [comment]
Thank you. Let me try and see if I can come back with a positive answer. 

Can I ask you what version of Python are you using?

**Comment by MisterBiggs** [comment]
Python 3.9

**Comment by MisterBiggs** [comment]
Pushed an update that should have fixed this. 

https://gitlab.com/simple-stock-bots/simple-telegram-stock-bot/-/issues/78
https://gitlab.com/simple-stock-bots/simple-telegram-stock-bot/-/commit/4f7aff9db22d35076bc473c4ecad3ca2d400317b

**Comment by sombra2** [comment]
Thank you. I'll try it and get back at you.
